--ORDERS DATA
INSERT INTO ORDERS VALUES(1, 'Cheeseburger', 'Fries', 15);
INSERT INTO ORDERS VALUES(2, 'Pizza', NULL, 8);
INSERT INTO ORDERS VALUES(3, 'Soup', 'Salad', 12);
INSERT INTO ORDERS VALUES(4, NULL, NULL, 0);
INSERT INTO ORDERS VALUES(5, 'Steak', 'Soup', 30);
INSERT INTO ORDERS VALUES(6, 'Waffles', 'Coffee', 10);
INSERT INTO ORDERS VALUES(7, 'Sandwich', 'Tea', 9);
INSERT INTO ORDERS VALUES(8, 'Cheeseburger', 'Fries', 15);
INSERT INTO ORDERS VALUES(9, 'Soup ', 'Chips', 9);
INSERT INTO ORDERS VALUES(10, 'Sandwich', 'Chips', 8);

--CUSTOMER DATA
INSERT INTO CUSTOMER VALUES(1, 'Alex', 1);
INSERT INTO CUSTOMER VALUES(2, 'Sara', 2);
INSERT INTO CUSTOMER VALUES(3, 'David', 3);
INSERT INTO CUSTOMER VALUES(4, 'John', 4);
INSERT INTO CUSTOMER VALUES(5, 'Sammy', 5);
INSERT INTO CUSTOMER VALUES(6, 'Katie', 6);
INSERT INTO CUSTOMER VALUES(7, 'Julie', 7);
INSERT INTO CUSTOMER VALUES(8, 'Ethan', 8);
INSERT INTO CUSTOMER VALUES(9, 'Drake', 9);
INSERT INTO CUSTOMER VALUES(10, 'Josh', 10);

--CHEF DATA
INSERT INTO CHEF VALUES(1, 'Sammy', 2);
INSERT INTO CHEF VALUES(2, 'Katie', 4);
INSERT INTO CHEF VALUES(3, 'Jim', 6);

--TICKET DATA
INSERT INTO TICKET VALUES(1, 1, 1);
INSERT INTO TICKET VALUES(2, 2, 2);
INSERT INTO TICKET VALUES(3, 3, 3);
INSERT INTO TICKET VALUES(4, 4, 3);
INSERT INTO TICKET VALUES(5, 5, 1);
INSERT INTO TICKET VALUES(6, 6, 2);
INSERT INTO TICKET VALUES(7, 7, 3);
INSERT INTO TICKET VALUES(8, 8, 2);
INSERT INTO TICKET VALUES(9, 9, 2);
INSERT INTO TICKET VALUES(10, 10, 1);

--DELIVERY DATA
INSERT INTO DELIVERY VALUES(1, 1, '23 Main St', 3);
INSERT INTO DELIVERY VALUES(2, 2, '1 Union Ave', 18);
INSERT INTO DELIVERY VALUES(3, 3, '12 East Ave', 2);
INSERT INTO DELIVERY VALUES(4, 4, '8 Pleasant St', 10);
INSERT INTO DELIVERY VALUES(5, 5, '32 Free St', 45);
INSERT INTO DELIVERY VALUES(6, 6, '90 Side St', 8);
INSERT INTO DELIVERY VALUES(7, 7, '77 South St', 2);
INSERT INTO DELIVERY VALUES(8, 8, '45 High St', 6);
INSERT INTO DELIVERY VALUES(9, 9, '8 North St', 10);
INSERT INTO DELIVERY VALUES(10, 10, '8 North St', 10);